spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5433/pfm
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/db-changelog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/PFM
          jwk-set-uri: http://localhost:8080/auth/realms/PFM/protocol/openid-connect/certs